name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
    
      - run: git fetch --force --tags
      - uses: actions/setup-go@main
        with:
          go-version: stable
      
      - run: ./build.sh

      - name: Create required instances
        env:
          REDMINE_TEST_API_KEY: ${{ secrets.REDMINE_TEST_API_KEY }}
          REDMINE_TEST_SQL_DUMP: ${{ secrets.REDMINE_TEST_SQL_DUMP }}
        run: tests/init.sh

      - name: create.sh
        run: |
          if ! sudo bash -xe tests/redmine/issue/create.sh; then
            cat /var/log/monokit.log
            exit 1
          fi

      #- name: update.sh
      #  run: tests/redmine/issue/update.sh
      
      - name: close.sh
        run: |
          if ! sudo bash -xe tests/redmine/issue/close.sh; then
            cat /var/log/monokit.log
            exit 1
          fi

