name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          
      - run: git fetch --force --tags
      - uses: actions/setup-go@main
        with:
          go-version: stable
      
      - run: ./build.sh

      - name: Create required instances
        env:
          REDMINE_TEST_API_KEY: ${{ secrets.REDMINE_TEST_API_KEY }}
          REDMINE_TEST_SQL_DUMP: ${{ secrets.REDMINE_TEST_SQL_DUMP }}
        run: tests/init.sh

      - name: create.sh
        run: sudo bash -xe tests/redmine/issue/create.sh

      #- name: update.sh
      #  run: tests/redmine/issue/update.sh
      
      - name: close.sh
        run: sudo bash -xe tests/redmine/issue/close.sh
